In [2]:
import numpy as np

### Soru 1
#### NumPy kullanarak 1’den 20’ye kadar sayılardan oluşan bir dizi oluşturun.
#### Dizinin kaç eleman içerdiğini ekrana yazdırın.

In [30]:
dizi = np.arange(1,21)

print(dizi)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [32]:
print("Eleman sayısı : " , dizi.size)

Eleman sayısı :  20


### Soru 2
#### [5, 10, 15, 20, 25] değerlerinden oluşan bir NumPy dizisi oluşturun.
#### Dizideki tüm elemanları 3 ile çarpın.
#### Sonucu ekrana yazdırın.

In [35]:
veri = np.array([5,10,15,20,25])

In [37]:
yeni = veri * 3

print(yeni)

[15 30 45 60 75]


### Soru 3
#### 0’dan 30’a kadar sayılar içeren bir dizi oluşturun.
#### Bu diziden sadece 10 ile 20 arasındaki elemanları slicing kullanarak seçin.

In [46]:
dizi = np.arange(0,30)

In [48]:
secim = dizi[10:21]

print(secim)

[10 11 12 13 14 15 16 17 18 19 20]


### Soru 4
#### [1,2,3] ve [4,5,6] dizilerini oluşturun.
#### Bu iki diziyi NumPy kullanarak birleştirin.

In [53]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [57]:
birles = np.concatenate((x,y))

print(birles)

[1 2 3 4 5 6]


### Soru 5
#### 1’den 12’ye kadar sayılar içeren bir dizi oluşturun.
#### Bu diziyi reshape kullanarak 3x4 boyutunda bir matrise dönüştürün.
#### Matrisin shape değerini yazdırın.

In [61]:
dizi = np.arange(1,13)

In [74]:
matris = dizi.reshape(3,4)

print(matris)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [76]:
matris.shape

(3, 4)

### Soru 6
#### Aşağıdaki matrisi oluşturun
##### [[1,2,3],
##### [4,5,6],
##### [7,8,9]]
#### İkinci satırı ekrana yazdırın.
#### İkinci sütunu ekrana yazdırın.

In [80]:
matris = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [82]:
matris[1]

array([4, 5, 6])

In [84]:
matris[:,1]

array([2, 5, 8])

### Soru 7
#### 3x3 boyutunda rastgele sayılardan oluşan bir matris oluşturun.
#### Matrisin ortalamasını hesaplayın.
#### Matrisin maksimum değerini yazdırın.

In [96]:
matris = np.random.rand(3,3)

print(matris)

[[0.34627421 0.46919776 0.20906991]
 [0.19519022 0.51605166 0.81744825]
 [0.97261805 0.02240974 0.63540217]]


In [98]:
np.mean(matris)

0.4648513297286525

In [100]:
np.max(matris)

0.9726180478766869

### Soru 8
#### [2,4,6,8] ve [1,3,5,7] dizilerini oluşturun.
#### Dizileri eleman bazlı çarpın.
#### Sonucu ekrana yazdırın

In [113]:
x = np.array([2,4,6,8])
y = np.array([1,3,5,7])

In [115]:
sonuc = x * y

In [117]:
print(sonuc)

[ 2 12 30 56]


### Soru 9
#### 1’den 9’a kadar sayılar içeren bir dizi oluşturun.
#### Bu diziyi 3x3 matrise dönüştürün.
#### Matrisin transpose’unu hesaplayın.

In [137]:
dizi = np.arange(1,10)
matris = dizi.reshape(3,3)

In [139]:
print(matris)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [141]:
transpose = matris.T

In [143]:
print(transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Soru 10
#### 1 ile 50 arasında rastgele 10 tam sayı üretin.
#### Bu sayılardan oluşan dizinin toplamını hesaplayın.
#### Dizinin ortalamasını yazdırın.

In [151]:
sayilar = np.random.randint(1,51,10)

print(sayilar)

[ 4  7 41 17  2  8 24 48 38 38]


In [156]:
np.sum(sayilar)

227

In [158]:
np.mean(sayilar)

22.7